version: "3"

services:
  sample:
    image: kniwase/wine-python-nuitka:3.11@sha256:0044e47fd4ab85480f7e677c52da69dbfddb41c8fb0d224811a7df727cf3539d
    platform: linux/amd64
    container_name: nuitka-cross-compiler-sample
    working_dir: /build
    volumes:
      - ./:/build
    command: wine python.exe -m nuitka ./main.py --mingw64 --onefile --standalone

